name: Publish to NuGet
on:  
  push:
    tags:
      - '*'

env:
  BUILD_CONFIG: Release
  SOLUTION: 'PseudoConsoleExample.sln'

  PROJECT: PseudoConsole.Core\PseudoConsole.Core.csproj

jobs:
  build:   

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: nuget restore ${{env.SOLUTION}}
      
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack 
      run: dotnet pack ${{env.PROJECT}}  --configuration Release --output nupkgs 

    - name: Publish to NuGet
      run: dotnet nuget push nupkgs/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

    # - name: Publish to NuGet

    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: ${{env.PROJECT}}
    #       NUGET_KEY: ${{secrets.NUGET_API_KEY}}

     
